### PR TITLE
Added Routes for questionpools, tests and courses

### PR DESCRIPTION
**Pull request by mat178**
Route for courses: 
- /courses/searchCourse/:ref_id
     /**
     * Retrieves all contents of a course.
     * (OPTIONAL) Results can be filtered by adding these parameters to the request:
     * "types": comma seperated list of all desired types of objects, e.g. "fold, tst"
     * "title": title of the objects
     * "description": description of the objects
     */

Routes for questionpools:
- /questionpools/getQuestions/:ref_id
      /**
     * Gets the questions of a Questionpool
     * (OPTIONAL) Desired types of questions can be specified in the 'types' parameter of the request 
     * e.g. "1,2,8" for single choice, multiple choice and text questions only.
     */

- /questionpools/getTextAnswers/:ref_id
     /**
     * Gets the answers for a question of type 8 = assTextQuestion
     */

- /questionpools/getSingleChoiceAnswers/:ref_id
     /**
     * Gets the answers for a question of type 1 = assSingleChoice
     */

- /questionpools/getMultipleChoiceAnswers/:ref_id
     /**
     * Gets the answers for a question of type 2 = assMultipleChoice
     */

Route for tests:
- /tests/getQuestions/:ref_id
     /**
     * Retrieves all questions of a test.
     * (OPTIONAL) Desired types of questions can be specified in the 'types' parameter of the request 
     * e.g. "1,2,8" for single choice, multiple choice and text questions only.
     */

### CODE REVIEW

**Comment by bastianleirpo** [comment]
+1

**Comment by Hufschmidt** [comment]
Will try to merge for next release...

**Comment by mat178** [comment]
any updates?

**Comment by Hufschmidt** [comment]
Terribly sorry for the long delay...

Merged with minimal changes. Although it should be noted, that the route can expose question-pool information when activated for an API-Key that is made public (eg. via a mobile-app) since there are no Role-Base-Access-Control (RBAC) checks. 
But to be fair and this is the reason I did accept the PR is that VERY FEW of our extensions currently do RBAC checks, mostly because they where written with server-to-server communication in mind, where an API-Key should mostly be kept private, thus preventing any third-party from abusing and information that could be gathered from activated API endpoint.

If you'd like to expose this API-Point publicly I would either use an additional ILIAS installation, where no sensitive question-pool data will be stored or take a look at [courses_v2/models/admin.php](https://github.com/hrz-unimr/Ilias.RESTPlugin/blob/master/RESTController/extensions/courses_v2/models/Admin.php#L315), making sure the check matches the one done by ILIAS on the GUI side when trying to access a question-pool.

BR

**Pull request merged**
